import React from 'react';
import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { act, isCompositeComponentWithType } from 'react-dom/test-utils';
import { Provider, useSelector } from 'react-redux';
import Button from '@mui/material/Button';

import store from '../controllers/redux/store';
import { InputModule } from './inputModule';
import { AddressInput } from './addressInput';

describe('inputModule - unit tests', () => {
  let dummy = false;
  it('dummy', () => {
    expect(dummy).toBe(false);
    dummy = true;
    expect(dummy).toBe(true);
  });
  it('InputModule renders', () => {
    render(<Provider store={store}><InputModule id='stopover.unit.test' /></Provider>);
    const component = screen.queryByTestId('stopover.unit.test');
    expect(component).toBeTruthy();
    isCompositeComponentWithType(component, InputModule);
    const start = screen.queryByTestId('stopover.unit.test.address-form-start');
    const end = screen.queryByTestId('stopover.unit.test.address-form-end');
    expect(start).toBeTruthy();
    isCompositeComponentWithType(start, AddressInput);
    expect(end).toBeTruthy();
    isCompositeComponentWithType(end, AddressInput);
    const creator = screen.queryByTestId('stopover.unit.test.generate-route');
    expect(creator).toBeTruthy();
    isCompositeComponentWithType(creator, Button);
    expect(creator.textContent).toMatch('Luo');
    expect(creator.textContent).toMatch('reitti');
    expect(creator.textContent).toMatch('Luo reitti');
  });
});

describe('inputModule - integration tests', () => {
  let dummy = false;
  it('dummy', () => {
    expect(dummy).toBe(false);
    dummy = true;
    expect(dummy).toBe(true);
  });
  it('AddressInput - start', () => {
    render(<Provider store={store}><InputModule id='stopover.integration.test' /></Provider>);
    const start = screen.queryByTestId('stopover.integration.test.address-form-start');
    expect(start).toBeTruthy();
    isCompositeComponentWithType(start, AddressInput);
    let state = store.getState().start;
    expect(state.street).toMatch('');
    expect(state.number).toMatch('');
    expect(state.municipality).toMatch('');
    expect(state.geocode).toBe(null);
    const street = within(start).getByLabelText('katu');
    const number = within(start).getByLabelText('numero');
    const municipality = within(start).getByLabelText('kunta');
    expect(street).toBeTruthy();
    expect(number).toBeTruthy();
    expect(municipality).toBeTruthy();
    expect(street.value).toBe('');
    expect(number.value).toBe('');
    expect(municipality.value).toBe('');
    act(() => {
      userEvent.type(street, 'Kaivokatu');
      userEvent.type(number, '2');
      userEvent.type(municipality, 'Helsinki');
    });
    expect(street.value).toBe('Kaivokatu');
    expect(number.value).toBe('2');
    expect(municipality.value).toBe('Helsinki');
    state = store.getState().start;
    expect(state.street).toMatch('Kaivokatu');
    expect(state.number).toMatch('2');
    expect(state.municipality).toMatch('Helsinki');
    act(() => userEvent.click(within(start).getByText('Aseta')));
    setTimeout(() => {
      expect(street.value).toBe('');
      expect(number.value).toBe('');
      expect(municipality.value).toBe('');
      state = store.getState().start;
      expect(state.street).toMatch('');
      expect(state.number).toMatch('');
      expect(state.municipality).toMatch('');
      expect(state.geocode).not.toBe(null);
    }, 3500);
  });
  it('AddressInput - end', () => {
    render(<Provider store={store}><InputModule id='stopover.integration.test' /></Provider>);
    const end = screen.queryByTestId('stopover.integration.test.address-form-end');
    expect(end).toBeTruthy();
    isCompositeComponentWithType(end, AddressInput);
    let state = store.getState().end;
    expect(state.street).toMatch('');
    expect(state.number).toMatch('');
    expect(state.municipality).toMatch('');
    expect(state.geocode).toBe(null);
    const street = within(end).getByLabelText('katu');
    const number = within(end).getByLabelText('numero');
    const municipality = within(end).getByLabelText('kunta');
    expect(street).toBeTruthy();
    expect(number).toBeTruthy();
    expect(municipality).toBeTruthy();
    expect(street.value).toBe('');
    expect(number.value).toBe('');
    expect(municipality.value).toBe('');
    act(() => {
      userEvent.type(street, 'Tietotie');
      userEvent.type(number, '14');
      userEvent.type(municipality, 'Vantaa');
    });
    expect(street.value).toBe('Tietotie');
    expect(number.value).toBe('14');
    expect(municipality.value).toBe('Vantaa');
    state = store.getState().end;
    expect(state.street).toMatch('Tietotie');
    expect(state.number).toMatch('14');
    expect(state.municipality).toMatch('Vantaa');
    act(() => userEvent.click(within(end).getByText('Aseta')));
    setTimeout(() => {
      expect(street.value).toBe('');
      expect(number.value).toBe('');
      expect(municipality.value).toBe('');
      state = store.getState().end;
      expect(state.street).toMatch('');
      expect(state.number).toMatch('');
      expect(state.municipality).toMatch('');
      expect(state.geocode).not.toBe(null);
    }, 3500);
  });
  it('InputModule - generate-route', () => {
    render(<Provider store={store}><InputModule id='stopover.integration.test' /></Provider>);
    let state_routes = store.getState().route;
    expect(state_routes.routes.length).toBe(0);
    const start = screen.queryByTestId('stopover.integration.test.address-form-start');
    expect(start).toBeTruthy();
    isCompositeComponentWithType(start, AddressInput);
    let state_start = store.getState().start;
    expect(state_start.street).toMatch('');
    expect(state_start.number).toMatch('');
    expect(state_start.municipality).toMatch('');
    expect(state_start.geocode).toBe(null);
    let street = within(start).getByLabelText('katu');
    let number = within(start).getByLabelText('numero');
    let municipality = within(start).getByLabelText('kunta');
    expect(street).toBeTruthy();
    expect(number).toBeTruthy();
    expect(municipality).toBeTruthy();
    expect(street.value).toBe('');
    expect(number.value).toBe('');
    expect(municipality.value).toBe('');
    act(() => {
      userEvent.type(street, 'Kaivokatu');
      userEvent.type(number, '2');
      userEvent.type(municipality, 'Helsinki');
    });
    expect(street.value).toBe('Kaivokatu');
    expect(number.value).toBe('2');
    expect(municipality.value).toBe('Helsinki');
    state_start = store.getState().start;
    expect(state_start.street).toMatch('Kaivokatu');
    expect(state_start.number).toMatch('2');
    expect(state_start.municipality).toMatch('Helsinki');
    expect(state_start.geocode).toBe(null);
    act(() => userEvent.click(within(start).getByText('Aseta')));
    setTimeout(() => {
      expect(street.value).toBe('');
      expect(number.value).toBe('');
      expect(municipality.value).toBe('');
      state_start = store.getState().start;
      expect(state_start.street).toMatch('');
      expect(state_start.number).toMatch('');
      expect(state_start.municipality).toMatch('');
      expect(state_start.geocode).not.toBe(null);
    }, 3500);
    const end = screen.queryByTestId('stopover.integration.test.address-form-end');
    expect(end).toBeTruthy();
    isCompositeComponentWithType(end, AddressInput);
    let state_end = store.getState().end;
    expect(state_end.street).toMatch('');
    expect(state_end.number).toMatch('');
    expect(state_end.municipality).toMatch('');
    expect(state_end.geocode).toBe(null);
    street = within(end).getByLabelText('katu');
    number = within(end).getByLabelText('numero');
    municipality = within(end).getByLabelText('kunta');
    expect(street).toBeTruthy();
    expect(number).toBeTruthy();
    expect(municipality).toBeTruthy();
    expect(street.value).toBe('');
    expect(number.value).toBe('');
    expect(municipality.value).toBe('');
    act(() => {
      userEvent.type(street, 'Tietotie');
      userEvent.type(number, '14');
      userEvent.type(municipality, 'Vantaa');
    });
    expect(street.value).toBe('Tietotie');
    expect(number.value).toBe('14');
    expect(municipality.value).toBe('Vantaa');
    state_end = store.getState().end;
    expect(state_end.street).toMatch('Tietotie');
    expect(state_end.number).toMatch('14');
    expect(state_end.municipality).toMatch('Vantaa');
    expect(state_end.geocode).toBe(null);
    act(() => userEvent.click(within(end).getByText('Aseta')));
    setTimeout(() => {
      expect(street.value).toBe('');
      expect(number.value).toBe('');
      expect(municipality.value).toBe('');
      state_end = store.getState().end;
      expect(state_end.street).toMatch('');
      expect(state_end.number).toMatch('');
      expect(state_end.municipality).toMatch('');
      expect(state_end.geocode).not.toBe(null);
    }, 3500);
    const creator = screen.queryByTestId('stopover.integration.test.generate-route');
    expect(creator).toBeTruthy();
    isCompositeComponentWithType(creator, Button);
    act(() => userEvent.click(creator));
    setTimeout(() => {
      state_start = store.getState().start;
      state_end = store.getState().end;
      expect(state_start.street).toMatch('');
      expect(state_start.number).toMatch('');
      expect(state_start.municipality).toMatch('');
      expect(state_start.geocode).toBe(null);
      expect(state_end.street).toMatch('');
      expect(state_end.number).toMatch('');
      expect(state_end.municipality).toMatch('');
      expect(state_end.geocode).toBe(null);
      state_routes = store.getState().route;
      expect(state_routes.routes.length).toBe(1);
    }, 3500);
  });
});
